Add the frame to pack3d
Authentise/pack3d pull request #1
Opened 2019-06-10 20:26 UTC by Minglunt

### Description
---

- Modified pack3d/cmd/pack3d/main.go and pack3d/pack3d/model.go.

- Add a frame to the software so that the final packing model will be in the frame.

- Add some notes on the scripts for better understanding.

- The frame now is 100*100*100, will make it changable later.

- It cannot ensure to output a result, especially for large number, working on this now and try to fix it. 
### Ticket(s):
---
- ch999

2019-06-10 21:12 UTC, far-authentise requested changes
Great start. A few small changes.

2019-06-10 21:12 UTC, far-authentise commented on cmd/pack3d/main.go
> +	boundsize := fauxgl.V(50.0, 50.0, 50.0)
maybe a  clearer variable name would be 'max_packing_size' or 'maximum_packing_area'  ? There are a lot of bounding boxes :)

2019-06-10 21:12 UTC, far-authentise commented on cmd/pack3d/main.go
> +	var stlsize []fauxgl.Vector
maybe  a better name would be 'naive_stl_size' or 'simple_stl_size' ? We should indicate it's a 'dumb' size of just adding max dimensions. 'dumb_stl_size' ?

2019-06-10 21:12 UTC, far-authentise commented on cmd/pack3d/main.go
> +		//fmt.Println(reflect.TypeOf(stlsize))
please remove these 2 test comments.

2019-06-10 21:12 UTC, far-authentise commented on pack3d/model.go
> +func (m *Model) ValidBound(i int, stlsize []fauxgl.Vector, boundsize fauxgl.Vector) bool {
Some kind of comment/description # True if the passed move it within maximum_packing_area, false in all other cases.

2019-06-11 08:27 UTC, Vadimkin reviewed
Great!

2019-06-11 08:27 UTC, Vadimkin commented on pack3d/model.go
> +		for s := -1; s <= 1; s += 2 {  // switch axis direction - or +
```suggestion
                axisDirections := [2]int{-1, 1}
                for _, s := range axisDirections {  // switch axis direction - or +
```

2019-06-12 16:35 UTC, far-authentise approved these changes
merge it.

2019-06-12 16:35 UTC, merged