The pack3d can output json file now
Authentise/pack3d pull request #6
Opened 2019-06-13 20:30 UTC by Minglunt

## Description:
- The pack3d can output json file now!
- Add ao output json file example.

## Ticket:
- ch1152

2019-06-13 20:37 UTC, far-authentise requested changes
Excellent start. A few updates to processing/naming for clarity.

2019-06-13 20:37 UTC, far-authentise commented on cmd/pack3d/main.go
> +	//"encoding/json"
remove this please.

2019-06-13 20:37 UTC, far-authentise commented on cmd/pack3d/main.go
> +	type Data struct {
please make a better type name. Examples:   model_placement, packing,  positioning. Something clearer than 'Data'

2019-06-13 20:37 UTC, far-authentise commented on cmd/pack3d/main.go
> +		filenames     []string
filename of what? source stl?  maybe 'sources_stls' or 'packing_stls' is a more clear name.

2019-06-13 20:37 UTC, far-authentise commented on cmd/pack3d/main.go
> +			b, err := json.Marshal(data)
please also make `b` into a better variable name. 'positions_json' may be a good. name.

2019-06-17 15:59 UTC, shirazkn requested changes
Most are optional. Only necessary change is the one regarding json-file name. 
Since we're stacking inputs into pack3d ("pack3d build xyz, file1 file2, runUUID... ") , maybe the next step is to implement a json-file (dict) input here as well? 

@far-authentise Would appreciate a review of my review

2019-06-17 15:59 UTC, shirazkn commented on cmd/pack3d/main.go
>  		if ntime >= 19990{
You can rename this to max_resets, or something appropriate.

2019-06-17 15:59 UTC, shirazkn commented on cmd/pack3d/main.go
> +			if time.Since(start).Seconds() <= 20{
20 should ideally be a variable like ntimes, something along the lines of max_try_time

2019-06-17 15:59 UTC, shirazkn commented on cmd/pack3d/main.go
> +			ioutil.WriteFile("output.json", positions_json, 0644)
I think this json file should be unique. Since packing and merging are not done back to back, "output.json" is going to sit unused for a while, so there'll be one "output.json" for each run created in that time. 

Maybe we can use <Run-UUID>.json

2019-06-17 15:59 UTC, shirazkn commented on cmd/pack3d/main.go
>  package main
Add a comment showing how this code is run, such as "pack3d {build_x, build_y .... "

2019-06-17 16:28 UTC, Minglunt commented on cmd/pack3d/main.go
>  		if ntime >= 19990{
I added the interpretation under the variable `ntime`. Hope that will help to understand better.

2019-06-17 16:30 UTC, Minglunt commented on cmd/pack3d/main.go
> +			if time.Since(start).Seconds() <= 20{
Same, added notes.

2019-06-17 16:31 UTC, Minglunt commented on cmd/pack3d/main.go
> +			ioutil.WriteFile("output.json", positions_json, 0644)
Sure, will make it unique for every .json file.

2019-06-19 17:54 UTC, merged